output {
  elasticsearch {
    hosts => ["${LS_ES_HOST_1:localhost:9200}", "${LS_ES_HOST_2:localhost:9200}", "${LS_ES_HOST_3:localhost:9200}"]
    ilm_enabled => false
    ecs_compatibility => "disabled"
  }
  #stdout { codec => rubydebug }
}
